"""Add Album and update Song

Revision ID: 01dd0eddbd69
Revises: 32a2d79c4d96
Create Date: 2026-03-31 22:31:15.491337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01dd0eddbd69'
down_revision: Union[str, Sequence[str], None] = '32a2d79c4d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('songs', sa.Column('album_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'songs', 'albums', ['album_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.drop_column('songs', 'album_id')
    op.drop_table('albums')
    # ### end Alembic commands ###
